services:
  - type: web
    name: granjita-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: OWNER_WHATSAPP
        sync: false
      - key: STORE_URL
        sync: false
      - key: WHATSAPP_AUTO_REPLY
        value: "true"
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: PUPPETEER_CACHE_DIR
        value: ./.puppeteer
    plan: starter
